config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only:[:index,:new,:create,:edit,:update] do
    resources :messages,only: [:index,:create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :user
belongs_to :group
mount_uploader :image, ImageUploader
validates :text_or_image, presence: true

private
  def text_or_image
    text.presence or image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def destroy
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.update(group_params)
    if @group
      redirect_to root_path, notice: "グループを更新しました"
    else
      render :edit
    end
  end

private
  def group_params
    params.require(:group).permit(:name, user_ids:[])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :set_group

  def index
    @messages = @group.messages.includes(:user)
    @new_message = Message.new
  end
  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice:"メッセージを送信しました"}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      @new_message = Message.new
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

private
  def message_params
    params.require(:message).permit(:text,:image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @results = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  -if @group.errors.any?
    .chat-group-form__errors
      %h2="#{@group.errors.full_messages.count}件のエラーがあります"
      %ul
        -@group.errors.full_messages.each do |message|
          %li="#{message}"
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, id: "chat_group_name", class:"chat-group-form__input",placeholder:"グループ名を入力してください"
  .chat-group-form__field
    .chat-group-form__field--left
      %label{class:"chat-group-form__label" , for:"chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input{class: "chat-group-form__input", id:"user-search-field", placeholder:"追加したいユーザー名を入力してください", type:"text"}
      #user-search-result
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label "チャットメンバー", class:"chat-group-form__label"
    .chat-group-form__field--right{id:"user-joined-in"}
      %input{type:"hidden", name:"group[user_ids][]", value:""}
        -@group.users.each do |user|
          .chat-group-user.clearfix
            %p{class:"chat-group-user__name"}
              =user.name
            .user-search-add.chat-group-user__btn.chat-group-user__btn--remove{"data-user-id": "#{user.id}","data-user-name": "#{user.name}"}削除
            %input{type:"hidden", value:"#{user.id}", checked:"checked", name:"group[user_ids][]", id:"group_user_ids_#{user.id}"}
  .chat-group-form__field
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class:"chat-group-form__action-btn"

app/views/groups/_group.html.haml
=link_to group_messages_path(group),{class:"leftside__groupbox__partial"} do
  %span.leftside__groupbox__partial__text--groupname
    =group.name
  %span.leftside__groupbox__partial__text--message
    -if group.messages.last.present?
      =group.messages.last.text? ? group.messages.last.text : "画像が投稿されている"
    -else
      ="メッセージはありません"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =render partial:"form", local:{group: @group}

app/views/groups/index.html.haml
.body__wrapper
  .leftside
    =render "./shared/left_side"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  =render partial:"form"

app/views/layouts/_popupbox.html.haml
.popupbox
  - flash.each do |key, value|
    = content_tag(:p, value, class: "popupbox__message popupbox__message__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Chatspace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .page__wrapper
      = render "./layouts/popupbox"
      = yield

app/views/messages/_message.html.haml
.rightside__chatbox__partial{"data-message-id": message.id}
  .rightside__chatbox__partial__wrapper
    %p.rightside__chatbox__partial__wrapper--text
      =message.user.name
    %p.rightside__chatbox__partial__wrapper--date
      =message.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d%H:%M:%S")
  %p.rightside__chatbox__partial__message
    =message.text if message.text.present?
  =image_tag message.image,{class:"rightside__chatbox__partial__image"} if message.image.present?

app/views/messages/index.html.haml
.body__wrapper
  .leftside
    =render "./shared/left_side"
  .rightside
    =render "./shared/right_side"

app/views/shared/_left_side.html.haml
.leftside__namebox
  %p.leftside__namebox__name
    =current_user.name
  = link_to new_group_path, class: "leftside__namebox__icon--edit" do
    = fa_icon 'edit'
  = link_to edit_user_path(current_user), class: "leftside__namebox__icon--cog" do
    = fa_icon 'cog'
.leftside__groupbox
  -current_user.groups.includes(:messages).each do |group|
    = render partial: "./groups/group", locals:{ group: group }

app/views/shared/_right_side.html.haml
.rightside__groupproperty
  .rightside__groupproperty__wrapper
    %p.rightside__groupproperty__wrapper--name
      = @group.name
    %p.rightside__groupproperty__wrapper--member
      Member:
      - @group.users.each do |user|
        = user.name
  =link_to "Edit",edit_group_path(params[:group_id]),class:"rightside__groupproperty__button"
.rightside__chatbox
  -if @messages
    = render partial:"./messages/message",collection: @messages 
=form_for [@group, @new_message] do |f|
  .rightside__messageform
    .rightside__messageform__textbox
      = f.text_field :text, {class:"rightside__messageform__textbox__text",placeholder: "type a message"}
      = f.label :image , {class:"rightside__messageform__textbox__logo"} do
        = fa_icon "picture-o"
        = f.file_field :image, {class:"rightside__messageform__textbox__logo--hidden"}
    = f.submit "Send",{class:"rightside__messageform__submit"}

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, class: 'btn',method: 'delete'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'